[package]
name = "mouselogrs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
input-linux-sys = "=0.9.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0"

[profile.release-with-debug]
inherits = "release"
debug = true
